const util = require('util');
const assert = require('assert');
const args = process.argv.slice(2);
const steps = parseInt(args[0], 10);
const insertions = parseInt(args[1], 10);
const targetPreceder = parseInt(args[2], 10);
const reportInterval = parseInt(args[3] || '1000000', 10);
assert(!isNaN(steps) && !isNaN(insertions) && !isNaN(targetPreceder), "must provide arguments: STEPS INSERTIONS NEIGHBOR (e.g. 394 2017 0): " + args.join(" "));
const {SpinLock} = require('./spinlock');
const lock = new SpinLock();
lock.iterate(steps, insertions, reportInterval);
const indexOfNeighbor = lock.nodes.indexOf(targetPreceder);
console.log(util.format("value after %s: %s", targetPreceder, lock.nodes[indexOfNeighbor + 1]));
